name: STM32

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
          project-type: library

  build:
    name: Test compiling
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arduino-boards-fqbn:
          - STMicroelectronics:stm32:GenF2:pnum=storm32

        include:
          - arduino-boards-fqbn: STMicroelectronics:stm32:GenF2:pnum=storm32
            platform-url: https://github.com/kemp-zz/Arduino-FOC/blob/master/src/STorM32-BGC_v1.31_RC
            sketch-names: storm32.ino

      # Do not cancel all jobs / architectures if one job fails
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install required board platform
      run: |
        PLATFORM=STMicroelectronics:stm32
        arduino-cli core update-index --additional-urls https://github.com/kemp-zz/Arduino-FOC/blob/master/src/STorM32-BGC_v1.31_RC.json > /dev/null
        arduino-cli core install STMicroelectronics:stm32 --additional-urls https://github.com/kemp-zz/Arduino-FOC/blob/master/src/STorM32-BGC_v1.31_RC.json > /dev/null
    - uses: ArminJo/arduino-test-compile@master
      with:
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
          sketch-names: ${{ matrix.sketch-names }}
          sketches-exclude: ${{ matrix.sketches-exclude }}
          build-properties: ${{ toJson(matrix.build-properties) }}


            
